const stationData = [
    { name: "Station 1" },
    { name: "Station 2" },
    { name: "Station 3" },
    { name: "Station A" },
    { name: "Station B" },
    { name: "Station X" },
    { name: "Station Y" },
    { name: "Station P" },
    { name: "Station Q" },
    { name: "Station C" },
    { name: "Station D" },
    { name: "Station M" },
    { name: "Station N" },
    { name: "Station E" },
    { name: "Station F" },
    { name: "Station G" },
    { name: "Station H" },
    { name: "Station I" },
    { name: "Station J" },
    { name: "Station K" },
    { name: "Station L" },
    { name: "Station O" },
    { name: "Station P" },
    { name: "Station R" },
    { name: "Station S" },
    { name: "Station T" },
    { name: "Station U" },
    { name: "Station V" },
    { name: "Station W" },
    { name: "Station X" },
    { name: "Station Y" },
    { name: "Station Z" },
    { name: "Station AA" },
  ];

export default stationData;
